name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build
      uses: ./.github/workflows/build

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/lineage-20.0'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: ${{ github.sha }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
